#! package-manifest: ./deploy/chart/catalog_resources/rh-operators/clusterlogging.v4.7.0.clusterserviceversion.yaml
packageName: cluster-logging
channels:
- name: "4.7"
  currentCSV: clusterlogging.v4.7.0
